title: Thierry Bizimungu
author: Thierry Bizimungu
email: thierry44@gmail.com
github_username: unknownv2
description: > # this means to ignore newlines until "baseurl:"
  Development blog.
theme: minima
